language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
matrix:
  include:
    - node_js: "4.0"
      env: BROWSER=true
before_install:
  - apt-get install nodejs-legacy
  - npm install -g npm
before_script:
  - npm install -g grunt
  - npm install --save-dep
script:
  - grunt test --verbose
notifications:
  email: false
after_success: npm run coveralls
